services:
  django:
    build: ./django/travels
    container_name: drf-backend
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    environment:
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1,drf-backend,react-frontend
      - FRONTEND_URL=http://localhost:5173

      - EMAIL_HOST_USER=2426tester@gmail.com
      - EMAIL_HOST_PASSWORD=xxvbgdhxypxksrob

      - RAZORPAY_KEY_ID=rzp_test_dnAdAp1u96caf5
      - RAZORPAY_KEY_SECRET=UzttVPPjiS5pXArasNmr5srn

  frontend:
    build: ./react/travels
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./react/travels:/app
      - /app/node_modules
    depends_on:
      - django