version: "3.9"

services:
  django:
    build: ./django/travels
    container_name: drf-backend
    ports:
      - "8000:8000"
    volumes:
      - ./django:/app
    env_file:
      - .env
    depends_on:
      - frontend

  frontend:
    build: ./react/travels
    container_name: react-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./react/travels:/app
      - /app/node_modules